services:
  rediska:
    image: redis:8.8.0-alpine3.23
    restart: always
    container_name: rediska
    command: redis-server --aclfile /etc/redis/users.acl && redis-server --appendonly yes
    volumes:
      - ./users.acl:/etc/redis/users.acl
    networks:
      - internal_network

  pg_db:
    image: postgres:17-alpine3.23
    container_name: pg_db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    restart: always
    networks:
      - internal_network

  mail:
    image: axllent/mailpit:latest
    container_name: mail
    restart: always
    ports:
      - "0.0.0.0:1025:1025"
      - "0.0.0.0:8025:8025"

  app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: app
    restart: always
    volumes:
      - ..:/app
    depends_on:
      - pg_db
      - rediska
      - mail
    networks:
      - internal_network

networks:
  internal_network:
    driver: bridge
