services:
  rediska:
    image: redis:8.8.0-alpine3.23
    restart: always
    container_name: rediska
    command: redis-server --aclfile /etc/redis/users.acl && redis-server --appendonly yes
    ports:
      - "0.0.0.0:6379:6379"
    volumes:
      - ./users.acl:/etc/redis/users.acl
    networks:
      - internal_network

  pg_db:
    image: postgres:17-alpine3.23
    container_name: pg_db
    env_file:
      - .env
    ports:
      - "0.0.0.0:5432:5432"
    restart: always
    networks:
      - internal_network

  app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: app
    restart: always
    volumes:
      - ..:/app
    depends_on:
      - pg_db
      - rediska
    networks:
      - internal_network

networks:
  internal_network:
    driver: bridge
